name: Build Dylib
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Theos
        run: |
          git clone --recursive https://github.com/theos/theos.git $HOME/theos
          echo "THEOS=$HOME/theos" >> $GITHUB_ENV

      - name: Build Tweak
        run: |
          make package FINALPACKAGE=1

      - name: Upload Dylib
        uses: actions/upload-artifact@v4
        with:
          name: VanHuy.dylib
          path: .theos/obj/debug/VanHuy.dylib
